services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mkkilkgmom
      POSTGRES_DB: notes_db
    volumes: 
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      JWT_SECRET: supersecret
      DB_USER: postgres
      DB_PASSWORD: mkkilkgmom
      DB_HOST: db
      DB_NAME: notes_db
      DB_PORT: 5432
      PORT: 3000
    ports:
      - "3000:3000"
    volumes:
      - ./server:/usr/src/app
    restart: unless-stopped
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.front
    container_name: notes-frontend
    ports:
      - "5174:80" 
    depends_on:
      - backend
    restart: unless-stopped
volumes:
  db_data:
    
